server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/massreservation
    username: postgres
    password: postgres
    platform: postgres
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 30
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 4
        order_inserts: true

mass:
  interval:
    days: 10

